#spring:
#  application:
#    name: cloudtest-user
#  cloud:
#    bus:
#      trace:
#        enabled: true
#  rabbitmq:
#    host: 192.168.0.100
#    port: 5672
#    username: northking
#    password: 123456
#management:
#  security:
#    enabled: false
server:
  port: 18092
eureka:
   client:
     healthcheck:
       enabled: true

jwt:
  expire: 3600 #过期时间

